// src/app/layout.tsx
import React from 'react';
import NavMenu from './component/NavMenu';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Bug-Source',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="grid grid-cols-[256px_1fr] min-h-screen">
            <div className="h-full">
                <NavMenu />
            </div>
            <div>
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}